web:
  container_name: som-nodeapp-container
  build: web
  ports:
    - "8080:8080"
  links:
    - mongo
  environment:
    NODE_ENV: production
mongo:
  container_name: som-mongo-container
  build: mongo
  ports:
    - "27017:27017"
